spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/mozip
    username: root
    password: mozip1234!

AdminMail:
  password: 'kckosrhwdhaffosc'
  id: 'mo.zip12345@gmail.com'
mail:
  smtp:
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: 'false'
      port: '465'
    starttls:
      required: 'true'
      enable: 'true'
    port: '465'
    auth: 'true'


